CREATE TABLE IF NOT EXISTS organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT,
    org_name TEXT,
    org_template BIGINT,
    org_price BIGINT,
    org_price_ip BIGINT,
    org_inn BIGINT,
    org_foundation VARCHAR,
    org_foundation_2 VARCHAR
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    max_user_id BIGINT,
    org_id BIGINT,
    user_time BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT
);

CREATE INDEX IF NOT EXISTS idx_users_user_id ON users (user_id);
CREATE INDEX IF NOT EXISTS idx_users_org_id ON users (org_id);
CREATE INDEX IF NOT EXISTS idx_users_max_user_id ON users (max_user_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_max_user_id_not_null
    ON users (max_user_id)
    WHERE max_user_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS invoices_ua (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number BIGINT,
    org_id BIGINT,
    org_name TEXT,
    org_inn BIGINT,
    org_count TEXT,
    org_price BIGINT,
    date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_id BIGINT,
    count BIGINT
);

CREATE TABLE IF NOT EXISTS invoices_av (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number BIGINT,
    org_id BIGINT,
    org_name TEXT,
    org_inn BIGINT,
    org_count TEXT,
    org_price BIGINT,
    date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_id BIGINT,
    count BIGINT
);

CREATE TABLE IF NOT EXISTS invoices_3 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number BIGINT,
    org_id BIGINT,
    org_name TEXT,
    org_inn BIGINT,
    org_count TEXT,
    org_price BIGINT,
    date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_id BIGINT,
    count BIGINT
);

CREATE TABLE IF NOT EXISTS invoices_ip (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number BIGINT,
    org_id BIGINT,
    org_name TEXT,
    org_inn BIGINT,
    org_count TEXT,
    org_price BIGINT,
    date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_id BIGINT,
    count BIGINT
);

CREATE INDEX IF NOT EXISTS idx_invoices_ip_org_id ON invoices_ip (org_id);
CREATE INDEX IF NOT EXISTS idx_invoices_ip_user_id ON invoices_ip (user_id);
CREATE INDEX IF NOT EXISTS idx_invoices_ip_date ON invoices_ip (date);