CREATE TABLE IF NOT EXISTS organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    org_name TEXT,
    org_template BIGINT,
    org_price BIGINT,
    org_price_ip BIGINT,
    org_inn BIGINT,
    org_foundation VARCHAR,
    org_foundation_2 VARCHAR,
    CONSTRAINT organizations_org_id_uk UNIQUE (org_id)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tg_user_id BIGINT,
    max_user_id BIGINT,
    org_id BIGINT NOT NULL,
    user_time BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT,
    CONSTRAINT users_identity_required_chk CHECK (tg_user_id IS NOT NULL OR max_user_id IS NOT NULL),
    CONSTRAINT users_tg_user_id_uk UNIQUE (tg_user_id),
    CONSTRAINT users_max_user_id_uk UNIQUE (max_user_id),
    CONSTRAINT users_org_id_fk
        FOREIGN KEY (org_id)
        REFERENCES organizations(org_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_users_tg_user_id ON users (tg_user_id);
CREATE INDEX IF NOT EXISTS idx_users_org_id ON users (org_id);
CREATE INDEX IF NOT EXISTS idx_users_max_user_id ON users (max_user_id);

CREATE TABLE IF NOT EXISTS invoices_ua (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number BIGINT,
    org_id BIGINT,
    org_name TEXT,
    org_inn BIGINT,
    org_count TEXT,
    org_price BIGINT,
    date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_id BIGINT,
    count BIGINT
);

CREATE TABLE IF NOT EXISTS invoices_av (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number BIGINT,
    org_id BIGINT,
    org_name TEXT,
    org_inn BIGINT,
    org_count TEXT,
    org_price BIGINT,
    date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_id BIGINT,
    count BIGINT
);

CREATE TABLE IF NOT EXISTS invoices_3 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number BIGINT,
    org_id BIGINT,
    org_name TEXT,
    org_inn BIGINT,
    org_count TEXT,
    org_price BIGINT,
    date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_id BIGINT,
    count BIGINT
);

CREATE TABLE IF NOT EXISTS invoices_ip (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number BIGINT,
    org_id BIGINT,
    org_name TEXT,
    org_inn BIGINT,
    org_count TEXT,
    org_price BIGINT,
    date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_id BIGINT,
    count BIGINT,
    worker_status TEXT NOT NULL DEFAULT 'new',
    worker_attempts INTEGER NOT NULL DEFAULT 0,
    worker_started_at TIMESTAMPTZ,
    worker_finished_at TIMESTAMPTZ,
    worker_error TEXT,
    worker_result_files TEXT[],
    worker_workspace_path TEXT,
    worker_id TEXT,
    CONSTRAINT invoices_ip_worker_status_chk CHECK (
        worker_status IN ('new', 'processing', 'done', 'error')
    )
);

CREATE INDEX IF NOT EXISTS idx_invoices_ip_org_id ON invoices_ip (org_id);
CREATE INDEX IF NOT EXISTS idx_invoices_ip_user_id ON invoices_ip (user_id);
CREATE INDEX IF NOT EXISTS idx_invoices_ip_date ON invoices_ip (date);
CREATE INDEX IF NOT EXISTS idx_invoices_ip_worker_status ON invoices_ip (worker_status);
CREATE INDEX IF NOT EXISTS idx_invoices_ip_worker_status_date ON invoices_ip (worker_status, date DESC);
